- id: packer-fmt
  name: Packer Format
  description: Rewrites HCL2 Packer config files to canonical format
  entry: packer fmt
  args: [-recursive, .]
  language: python
  files: \.pkr(?:vars)?\.hcl$
  pass_filenames: false
