ci:
  autofix_prs: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  - id: check-json
  - id: check-yaml
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.8.0
  hooks:
  - id: setup-cfg-fmt
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
  - id: ruff
    args: [--fix, --show-fixes]
  - id: ruff-format
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.0
  hooks:
  - id: check-github-workflows
  - id: check-renovate
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: local
  hooks:
  - id: git-diff
    name: git diff
    entry: git diff --exit-code
    language: system
    pass_filenames: false
    always_run: true
# todo: pre-commit-update-hook
