name: main

on:
  push:
    branches: [main, test-me-*]
    tags: ['*']
  pull_request:

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@a24cbd9649beb9074bb3f36a598632264eda0803 # v1.8.1
    with:
      env: '["py39"]'
      os: windows-latest
      wheel-tags: true
  main-macos:
    uses: asottile/workflows/.github/workflows/tox.yml@a24cbd9649beb9074bb3f36a598632264eda0803 # v1.8.1
    with:
      env: '["py39"]'
      os: macos-latest
      wheel-tags: true
  main-macos-intel:
    uses: asottile/workflows/.github/workflows/tox.yml@a24cbd9649beb9074bb3f36a598632264eda0803 # v1.8.1
    with:
      env: '["py39"]'
      os: macos-13
      wheel-tags: true
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@a24cbd9649beb9074bb3f36a598632264eda0803 # v1.8.1
    with:
      env: '["py39"]'
      os: ubuntu-latest
